# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/murase/work/oop_nodes_genetic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/murase/work/oop_nodes_genetic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/murase/work/oop_nodes_genetic/CMakeFiles /Users/murase/work/oop_nodes_genetic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/murase/work/oop_nodes_genetic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named oop_nodes_genetic

# Build rule for target.
oop_nodes_genetic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oop_nodes_genetic
.PHONY : oop_nodes_genetic

# fast build rule for target.
oop_nodes_genetic/fast:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/build
.PHONY : oop_nodes_genetic/fast

Functions.o: Functions.cpp.o

.PHONY : Functions.o

# target to build an object file
Functions.cpp.o:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/Functions.cpp.o
.PHONY : Functions.cpp.o

Functions.i: Functions.cpp.i

.PHONY : Functions.i

# target to preprocess a source file
Functions.cpp.i:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/Functions.cpp.i
.PHONY : Functions.cpp.i

Functions.s: Functions.cpp.s

.PHONY : Functions.s

# target to generate assembly for a file
Functions.cpp.s:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/Functions.cpp.s
.PHONY : Functions.cpp.s

Node.o: Node.cpp.o

.PHONY : Node.o

# target to build an object file
Node.cpp.o:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/Node.cpp.o
.PHONY : Node.cpp.o

Node.i: Node.cpp.i

.PHONY : Node.i

# target to preprocess a source file
Node.cpp.i:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/Node.cpp.i
.PHONY : Node.cpp.i

Node.s: Node.cpp.s

.PHONY : Node.s

# target to generate assembly for a file
Node.cpp.s:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/Node.cpp.s
.PHONY : Node.cpp.s

oop_nodes_genetic.o: oop_nodes_genetic.cpp.o

.PHONY : oop_nodes_genetic.o

# target to build an object file
oop_nodes_genetic.cpp.o:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/oop_nodes_genetic.cpp.o
.PHONY : oop_nodes_genetic.cpp.o

oop_nodes_genetic.i: oop_nodes_genetic.cpp.i

.PHONY : oop_nodes_genetic.i

# target to preprocess a source file
oop_nodes_genetic.cpp.i:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/oop_nodes_genetic.cpp.i
.PHONY : oop_nodes_genetic.cpp.i

oop_nodes_genetic.s: oop_nodes_genetic.cpp.s

.PHONY : oop_nodes_genetic.s

# target to generate assembly for a file
oop_nodes_genetic.cpp.s:
	$(MAKE) -f CMakeFiles/oop_nodes_genetic.dir/build.make CMakeFiles/oop_nodes_genetic.dir/oop_nodes_genetic.cpp.s
.PHONY : oop_nodes_genetic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... oop_nodes_genetic"
	@echo "... Functions.o"
	@echo "... Functions.i"
	@echo "... Functions.s"
	@echo "... Node.o"
	@echo "... Node.i"
	@echo "... Node.s"
	@echo "... oop_nodes_genetic.o"
	@echo "... oop_nodes_genetic.i"
	@echo "... oop_nodes_genetic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

